# wrangler.toml
name = "kosher-snake-game"
main = "_worker.js"
compatibility_date = "2024-05-29" # It's good practice to set this to the date you develop/deploy.

[assets]
directory = "public" # This is where your static files are located.
binding = "ASSETS"